# Generated by Django 4.2 on 2024-08-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_view_article', 'Can view article'), ('can_add_article', 'Can add article'), ('can_change_article', 'Can change article'), ('can_delete_article', 'Can delete article')]},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': [('can_view_tag', 'Can view tag'), ('can_add_tag', 'Can add tag'), ('can_change_tag', 'Can change tag'), ('can_delete_tag', 'Can delete tag')]},
        ),
    ]
